### ISSUE TITLE
不兼容 nginx 1.11

### ISSUE THREAD

**Issue by xianhuawei** [eleme/nginx-udp#1]
编译报错

/root/nginx-udp-master/ngx_http_udp_module.c:22:5: error: unknown type name ‘ngx_udp_connection_t’
     ngx_udp_connection_t *udp_connection;
     ^
/root/nginx-udp-master/ngx_http_udp_module.c:43:27: error: unknown type name ‘ngx_udp_connection_t’
 ngx_int_t ngx_udp_connect(ngx_udp_connection_t *udpconn);
                           ^
/root/nginx-udp-master/ngx_http_udp_module.c: In function ‘ngx_http_udp_send’:
/root/nginx-udp-master/ngx_http_udp_module.c:121:5: error: unknown type name ‘ngx_udp_connection_t’
     ngx_udp_connection_t  *udpconn;
     ^
/root/nginx-udp-master/ngx_http_udp_module.c:125:16: error: request for member ‘connection’ in something not a structure or union
     if (udpconn->connection == NULL) {
                ^
/root/nginx-udp-master/ngx_http_udp_module.c:127:16: error: request for member ‘log’ in something not a structure or union
         udpconn->log = *endpoint->log;
                ^
/root/nginx-udp-master/ngx_http_udp_module.c:128:16: error: request for member ‘log’ in something not a structure or union
         udpconn->log.handler = NULL;
                ^
/root/nginx-udp-master/ngx_http_udp_module.c:129:16: error: request for member ‘log’ in something not a structure or union
         udpconn->log.data = NULL;
                ^
/root/nginx-udp-master/ngx_http_udp_module.c:130:16: error: request for member ‘log’ in something not a structure or union
         udpconn->log.action = "logging";
                ^
/root/nginx-udp-master/ngx_http_udp_module.c:132:9: error: implicit declaration of function ‘ngx_udp_connect’ [-Werror=implicit-function-declaration]
         if(ngx_udp_connect(udpconn) != NGX_OK) {
         ^
/root/nginx-udp-master/ngx_http_udp_module.c:133:23: error: request for member ‘connection’ in something not a structure or union
             if(udpconn->connection != NULL) {
                       ^
/root/nginx-udp-master/ngx_http_udp_module.c:134:44: error: request for member ‘connection’ in something not a structure or union
                 ngx_free_connection(udpconn->connection);
                                            ^
/root/nginx-udp-master/ngx_http_udp_module.c:135:24: error: request for member ‘connection’ in something not a structure or union
                 udpconn->connection = NULL;
                        ^
/root/nginx-udp-master/ngx_http_udp_module.c:141:16: error: request for member ‘connection’ in something not a structure or union
         udpconn->connection->data = endpoint;
                ^
/root/nginx-udp-master/ngx_http_udp_module.c:142:16: error: request for member ‘connection’ in something not a structure or union
         udpconn->connection->read->handler = ngx_http_udp_dummy_handler;
                ^
/root/nginx-udp-master/ngx_http_udp_module.c:143:16: error: request for member ‘connection’ in something not a structure or union
         udpconn->connection->read->resolver = 0;
                ^
/root/nginx-udp-master/ngx_http_udp_module.c:146:25: error: request for member ‘connection’ in something not a structure or union
     n = ngx_send(udpconn->connection, buf, len);
                         ^

**Comment by thbourlove** [comment]
这个不准备兼容，我们只支持tengine2.1及以上版本。
